version: "3.4"

services:
    api:
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8080:80"
        depends_on:
            - db
        environment:
            - ASPNETCORE_URLS=http://+:80
        env_file:
            -   .env

    db:
        image: "mcr.microsoft.com/mssql/server:2022-latest"
        ports:
            - "1433:1433"

        environment:
            SA_PASSWORD: "S3cur3P@ssW0rd!"
            ACCEPT_EULA: "Y"
